AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - staging
      - prod
    Default: staging
    Description: Stage that can be added to resource names

Mappings:
  EnvironmentResourceMapping:
    DynamoDbARN:
      staging: "arn:aws:dynamodb:us-east-1:285893673875:table/STAGING_TABLE/stream/2019-01-10T15:54:31.721"
      prod: "arn:aws:dynamodb:us-east-1:285893673875:table/PROD_TABLE/stream/2019-01-10T15:55:22.598"  

Resources:
  DynamoStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: app/
      Runtime: nodejs8.10
      Policies: AWSLambdaBasicExecutionRole
      Environment:
          Variables:
            DYNAMODB_ARN:
              Fn::FindInMap:
              - EnvironmentResourceMapping
              - DynamoDbARN
              - {Ref: Stage}
      KmsKeyArn: arn:aws:kms:us-east-1:285893673875:key/d9cef297-06e9-4c87-b82c-e66598891d20
  DynamoStreamFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      StartingPosition: TRIM_HORIZON
      EventSourceArn: arn:aws:dynamodb:us-east-1:285893673875:table/STAGING_TABLE/stream/2019-01-10T15:54:31.721
      FunctionName: !GetAtt DynamoStreamFunction.Arn
