AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - staging
      - prod
    Default: staging
    Description: Stage that can be added to resource names

Conditions:
  isStaging: !Not [ !Equals [!Ref Stage, '']]
  isProduction: !Not [ !Equals [!Ref Stage, '']]

Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: app/
      Runtime: nodejs8.10
      Policies: AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          STAGING : ${isStaging}
          PRODUCTION : ${isProduction}
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      KmsKeyArn: arn:aws:kms:us-east-1:285893673875:key/d9cef297-06e9-4c87-b82c-e66598891d20
Outputs:
  ApiUrl:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: !Sub 'api-url-${Stage}'
