AWSTemplateFormatVersion: '2010-09-09'
Description: Outputs the time
Resources:
  TimeFunction:
    Properties:
      CodeUri: s3://codepipeline-us-east-1-983952263258/b35e6fce515c083e80f33f528c4b080c
      Events:
        MyTimeApi:
          Properties:
            Method: GET
            Path: /TimeResource
          Type: Api
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
