AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HelloWorldFunction:
    Properties:
      CodeUri: s3://danstanhope/c595aeef891cf19ece04f5d250460821
      Events:
        HelloWorldApi:
          Properties:
            Method: GET
            Path: /
          Type: Api
      Handler: index.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
